import os
import uuid
import pdfplumber
import re
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

app = FastAPI()

# NU Grade Mapping
GRADE_POINTS = {'A+': 4.00, 'A': 3.75, 'A-': 3.50, 'B+': 3.25, 'B': 3.00, 'B-': 2.75, 'C+': 2.50, 'C': 2.25, 'D': 2.00, 'F': 0.00}

# Use /tmp for production (Render/Koyeb requirement)
TMP_DIR = "/tmp" if os.environ.get("RENDER") else "uploads"
if not os.path.exists(TMP_DIR):
    os.makedirs(TMP_DIR)

from reportlab.lib.units import inch

def generate_report(student, courses, gpa, filename):
    path = os.path.join(TMP_DIR, filename)
    doc = SimpleDocTemplate(path, pagesize=A4, rightMargin=50, leftMargin=50, topMargin=50, bottomMargin=50)
    elements = []
    styles = getSampleStyleSheet()

    # Title & Header
    styles['Title'].fontSize = 22
    styles['Title'].textColor = colors.HexColor("#1e40af")
    elements.append(Paragraph("ACADEMIC TRANSCRIPT REPORT", styles['Title']))
    elements.append(Paragraph("National University, Bangladesh", styles['Normal']))
    elements.append(Spacer(1, 0.4 * inch))

    # Student Data Table
    student_data = [
        [Paragraph(f"<b>Name:</b> {student['name']}", styles['Normal']), 
         Paragraph(f"<b>Reg No:</b> {student['reg']}", styles['Normal'])]
    ]
    st_table = Table(student_data, colWidths=[3*inch, 3*inch])
    elements.append(st_table)
    elements.append(Spacer(1, 0.3 * inch))

    # Main Result Table
    data = [["COURSE CODE", "COURSE TITLE", "CREDIT", "GRADE", "POINTS"]]
    for c in courses:
        data.append([c['code'], c['title'][:40], c['credit'], c['grade'], f"{c['gp']:.2f}"])

    # Professional Table Styling
    t = Table(data, colWidths=[1*inch, 3*inch, 0.7*inch, 0.7*inch, 0.7*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1e40af")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('ALIGN', (1, 1), (1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#f8fafc")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f1f5f9")])
    ]))
    elements.append(t)
    
    # Summary Section
    elements.append(Spacer(1, 0.5 * inch))
    summary_data = [
        ["", f"TOTAL CALCULATED GPA: {gpa:.2f}"]
    ]
    summary_table = Table(summary_data, colWidths=[4*inch, 2.1*inch])
    summary_table.setStyle(TableStyle([
        ('FONTNAME', (1, 0), (1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (1, 0), (1, 0), 14),
        ('TEXTCOLOR', (1, 0), (1, 0), colors.HexColor("#1e40af")),
        ('ALIGN', (1, 0), (1, 0), 'RIGHT'),
    ]))
    elements.append(summary_table)

    # Footer Branding
    elements.append(Spacer(1, 1 * inch))
    elements.append(Paragraph("<hr/>", styles['Normal']))
    footer_text = "Report generated by NU CGPA Master | Developer: Rony Hassan Revan"
    elements.append(Paragraph(f"<font size='8' color='grey'>{footer_text}</font>", styles['Normal']))

    doc.build(elements)
    return filename

@app.get("/")
async def home():
    with open("index.html", "r") as f:
        return HTMLResponse(content=f.read())

@app.post("/process")
async def process_pdf(file: UploadFile = File(...)):
    unique_id = uuid.uuid4().hex[:8]
    input_path = os.path.join(TMP_DIR, f"in_{unique_id}.pdf")
    
    with open(input_path, "wb") as buffer:
        buffer.write(await file.read())

    student_info = {"name": "Unknown", "reg": "Unknown"}
    all_courses = []

    try:
        with pdfplumber.open(input_path) as pdf:
            for page in pdf.pages:
                text = page.extract_text()
                if not text: continue
                
                # Info Extraction
                for line in text.split('\n'):
                    if "Name" in line: student_info['name'] = line.split("Name")[-1].replace(":","").strip()
                    if "Registration" in line: 
                        regs = re.findall(r'\d+', line)
                        if regs: student_info['reg'] = regs[0]

                # Result Extraction (Regex Fallback included)
                tables = page.extract_tables()
                for table in tables:
                    for row in table:
                        row = [str(c).strip() if c else "" for c in row]
                        if len(row) >= 4:
                            code, credit_str, grade = row[0], row[-2], row[-1].upper()
                            if credit_str.isdigit() and grade in GRADE_POINTS:
                                all_courses.append({"code": code, "title": row[1], "credit": int(credit_str), "grade": grade, "gp": GRADE_POINTS[grade]})

                if len(all_courses) < 1:
                    regex_pattern = r"(\d{6})\s+(.*?)\s+(\d)\s+([A-F][+-]?)"
                    matches = re.findall(regex_pattern, text)
                    for m in matches:
                        if m[3] in GRADE_POINTS:
                            all_courses.append({"code": m[0], "title": m[1].strip(), "credit": int(m[2]), "grade": m[3], "gp": GRADE_POINTS[m[3]]})

        if not all_courses:
            return JSONResponse(status_code=400, content={"message": "No results found."})

        total_pts = sum(c['gp'] * c['credit'] for c in all_courses)
        total_credits = sum(c['credit'] for c in all_courses)
        gpa = round(total_pts / total_credits, 2)

        report_file = generate_report(student_info, all_courses, gpa, f"Result_{unique_id}.pdf")

        return {
            "status": "success",
            "student": student_info,
            "courses": all_courses,
            "gpa": gpa,
            "download_url": f"/download/{report_file}"
        }
    except Exception as e:
        return JSONResponse(status_code=500, content={"message": str(e)})

@app.get("/download/{filename}")
async def download(filename: str):
    file_path = os.path.join(TMP_DIR, filename)
    return FileResponse(file_path)

if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)